export interface ITeam {
    current_event_fixture: string[] ,
    next_event_fixture: string[],
    name: String,
    code: Number,
    short_name: String,
    unavailable: Boolean,
    strength: Number,
    position: Number,
    played: Number,
    win: Number,
    loss: Number,
    draw: Number,
    points: Number,
    form: Number,
    link_url: String,
    strength_overall_home: Number,
    strength_overall_away: Number,
    strength_attack_home: Number,
    strength_attack_away: Number,
    strength_defence_home: Number,
    strength_defence_away: Number,
    team_division: Number
}