var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var playerModel = new Schema({
    id: { type: Number },
    photo: { type: String },
    web_name: { type: String },
    team_code: { type: Number },
    status: { type: String },
    code: { type: Number },
    first_name: { type: String },
    second_name: { type: String },
    squad_number: { type: Number },
    news: { type: String},
    now_cost: { type: Number },
    news_added: { type: String },
    chance_of_playing_this_round: { type: Number },
    chance_of_playing_next_round: { type: Number },
    value_form: { type: String },
    value_season: { type: String },
    cost_change_start: { type: Number },
    cost_change_event: { type: Number },
    cost_change_start_fall: { type: Number },
    cost_change_event_fall: { type: Number },
    in_dreamteam: { type: Boolean },
    dreamteam_count: { type: Number },
    selected_by_percent: { type: String },
    form: { type: String },
    transfers_out: { type: Number },
    transfers_in: { type: Number },
    transfers_out_event: { type: Number },
    transfers_in_event: { type: Number },
    loans_in: { type: Number },
    loans_out: { type: Number },
    loaned_in: { type: Number },
    loaned_out: { type: Number },
    total_points: { type: Number },
    event_points: { type: Number },
    points_per_game: { type: String },
    ep_this: { type: String },
    ep_next: { type: String },
    special: { type: Boolean },
    minutes: { type: Number },
    goals_scored: { type: Number },
    assists: { type: Number },
    clean_sheets: { type: Number },
    goals_conceded: { type: Number },
    own_goals: { type: Number },
    penalties_saved: { type: Number },
    penalties_missed: { type: Number },
    yellow_cards: { type: Number },
    red_cards: { type: Number },
    saves: { type: Number },
    bonus: { type: Number },
    bps: { type: Number },
    influence: { type: String },
    creativity: { type: String },
    threat: { type: String },
    ict_index: { type: String },
    ea_index: { type: Number },
    element_type: { type: Number },
    team: { type: Number }
});

module.exports = mongoose.model('player', playerModel);